import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "OurDay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-[#F9F6F4]">{children}</body>
    </html>
  );
}
